[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "asl-sign-language-classifier"
version = "0.1.0"
description = "A Project for Classifying ASL."
authors = [
    {name = "Lineax17", email = "lineax17@gmail.com"}
]
dependencies = [
    "tensorflow[and-cuda]>=2.15.0",
    "opencv-python>=4.7.0.68",
    "mediapipe>=0.10.0",
    "h5py>=3.10",
    "pandas>=1.5.0",
    "keras-tuner>=1.1.0",
    "matplotlib>=3.5.0",
    "numpy>=1.21.0"
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "flake8"
]